### ISSUE TITLE
Enable hot-reloading Docker dev setup

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/R2-D2#11]
Currently, during development, the Docker image needs to be rebuilt every time there is a change, which slows down testing. Hot reloading would make this a lot smoother.
Tutorial: https://levelup.gitconnected.com/docker-for-go-development-a27141f36ba9

**Comment by juozasget** [comment]
Hi, I'd love to help with this one during Hacktoberfest :)

**Comment by ghostwriternr** [comment]
Hi @juozasget! Sure : ) Looking forward to your PR.

**Comment by feildrixliemdra** [comment]
Does this enhancement done yet ? @ghostwriternr
